"""Integration test: Alembic migrations actually apply against a real SQLite file.

Exercises alembic.ini + alembic/env.py + the autogenerated migration
together - the class of mistake (missing data-directory creation, wrong
FK/table creation order, a broken revision chain) that unit tests of the
ORM models alone would never catch. Assumes cwd == backend/ (matches
every documented test command in this project).
"""

import sqlite3
from pathlib import Path

from alembic import command
from alembic.config import Config
from app.core.config import get_settings

BACKEND_DIR = Path(__file__).resolve().parents[2]
ALEMBIC_INI = BACKEND_DIR / "alembic.ini"

EXPECTED_TABLES = {
    "tenants",
    "users",
    "documents",
    "chunks",
    "sessions",
    "messages",
    "message_citations",
    "feedback",
    "query_logs",
    "audit_logs",
    "alembic_version",
}


def _alembic_config() -> Config:
    cfg = Config(str(ALEMBIC_INI))
    cfg.set_main_option("script_location", str(BACKEND_DIR / "alembic"))
    return cfg


def _tables(db_path: Path) -> set[str]:
    conn = sqlite3.connect(db_path)
    try:
        return {row[0] for row in conn.execute("SELECT name FROM sqlite_master WHERE type='table'")}
    finally:
        conn.close()


def test_upgrade_head_creates_all_tables(tmp_path, monkeypatch):
    db_path = tmp_path / "migration_test.db"
    monkeypatch.setenv("DATABASE_URL", f"sqlite:///{db_path.as_posix()}")
    get_settings.cache_clear()

    try:
        command.upgrade(_alembic_config(), "head")
        assert EXPECTED_TABLES <= _tables(db_path)
    finally:
        get_settings.cache_clear()


def test_downgrade_base_then_upgrade_head_is_reversible(tmp_path, monkeypatch):
    db_path = tmp_path / "migration_reversible.db"
    monkeypatch.setenv("DATABASE_URL", f"sqlite:///{db_path.as_posix()}")
    get_settings.cache_clear()

    try:
        cfg = _alembic_config()
        command.upgrade(cfg, "head")
        command.downgrade(cfg, "base")
        assert _tables(db_path) == {"alembic_version"}

        command.upgrade(cfg, "head")
        assert EXPECTED_TABLES <= _tables(db_path)
    finally:
        get_settings.cache_clear()
